REMATCH_HQ:
  TEST_CHANNEL_ID: 1469333283795107840
  SERVER_ID: 1467945622400139528
  RESULTS_TOURNAMENTS_CHANNEL_ID: 1469058051742109808
  UPCOMING_TOURNAMENTS_CHANNEL_ID: 1469058701217239090
  LEADERBOARD_CHANNEL_ID: 1470487746312142869
  ROSTERS_CHANNEL_ID: 1473017185667383368
  TOURNAMENTS_PING_ID: 1469069527701786675
  SCRIM_FORUM_CHANNEL_ID: 1472621331395772509
  SCRIM_FORUM_USER_ID_EXCLUDE: 558112326058901516 # azizfcb

REMATCH_PART:
  SERVER_ID: 1448081638931173500
  EMBED_COLOR:
    PRT: 0x043949
    ART: 0x210010
  TOURNAMENT_INFO_CHANNEL_ID:
    PRT: 1463201095974129964
    ART: 1448084662688677919
  PRIZE_POOL:
    PRT: 50
    ART: 0
  HALL_OF_FAME_CHANNEL_ID:
    PRT: 1463211278347796519
    ART: 1448084718389039124
  SPONSORS_CHANNEL_ID:
    PRT: 1466925904558293032
